import{a as S,S as E,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();const q="51572255-4a923f4e22b79815f5c68f565",v="https://pixabay.com/api/",P=15;async function h(e,o=1){const n=new URLSearchParams({key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:P});try{return(await S.get(`${v}?${n}`)).data}catch(r){throw console.error("Error fetching images:",r),new Error("Failed to fetch images from Pixabay API")}}let d;function m(){d=new E(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.9})}function f(){d?d.refresh():m()}function y(e){const o=document.querySelector(".gallery");o.innerHTML="";const n=e.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy">
        <div class="info">
          <p><b>Likes:</b> ${r.likes}</p>
          <p><b>Views:</b> ${r.views}</p>
          <p><b>Comments:</b> ${r.comments}</p>
          <p><b>Downloads:</b> ${r.downloads}</p>
        </div>
      </a>
    </li>
  `).join("");o.insertAdjacentHTML("beforeend",n),f()}function M(){const e=document.querySelector(".gallery");e.innerHTML=""}function g(){document.querySelector(".loader").classList.remove("is-hidden")}function p(){document.querySelector(".loader").classList.add("is-hidden")}function L(){document.querySelector(".load-more").classList.remove("is-hidden")}function b(){document.querySelector(".load-more").classList.add("is-hidden")}function R(){document.querySelector(".end-message").classList.remove("is-hidden")}function $(){document.querySelector(".end-message").classList.add("is-hidden")}const O=document.querySelector(".form"),x=document.querySelector(".load-more");let i=1,u="",c=0;m();O.addEventListener("submit",B);x.addEventListener("click",A);async function B(e){e.preventDefault();const o=e.target.elements.searchQuery.value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}u=o,i=1,b(),$(),M(),g();try{const n=await h(u,i);if(c=n.totalHits,n.hits.length===0){a.error({title:"Error",message:"No images found. Please try another query!",position:"topRight"});return}y(n.hits),f(),H(n.hits.length)&&L(),a.success({title:"Success",message:`Found ${c} images`,position:"topRight"})}catch(n){w(n)}finally{p()}}async function A(){i++,g(),b();try{const e=await h(u,i);y(e.hits),f(),_(),I()?R():L()}catch(e){w(e)}finally{p()}}function H(e){return e>=15&&i*15<c}function I(){return i*15>=c}function _(){const e=document.querySelector(".gallery");if(!e.firstElementChild)return;const{height:o}=e.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}function w(e){console.error("Error:",e),a.error({title:"Error",message:"Failed to load images. Please try again later.",position:"topRight"})}
//# sourceMappingURL=index.js.map
