import{a as w,S,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();const E="51572255-4a923f4e22b79815f5c68f565",q="https://pixabay.com/api/",v=15;async function u(e,s=1){const r=new URLSearchParams({key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:v});try{return(await w.get(`${q}?${r}`)).data}catch(o){throw console.error("Error fetching images:",o),new Error("Failed to fetch images from Pixabay API")}}let f;function P(){f=new S(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.9})}function h(){f.refresh()}function m(e){const s=document.querySelector(".gallery"),r=e.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy">
        <div class="info">
          <p><b>Likes:</b> ${o.likes}</p>
          <p><b>Views:</b> ${o.views}</p>
          <p><b>Comments:</b> ${o.comments}</p>
          <p><b>Downloads:</b> ${o.downloads}</p>
        </div>
      </a>
    </li>
  `).join("");s.insertAdjacentHTML("beforeend",r)}function R(){const e=document.querySelector(".gallery");e.innerHTML=""}function y(){document.querySelector(".loader").classList.remove("is-hidden")}function g(){document.querySelector(".loader").classList.add("is-hidden")}function p(){document.querySelector(".load-more").classList.remove("is-hidden")}function L(){document.querySelector(".load-more").classList.add("is-hidden")}function M(){document.querySelector(".end-message").classList.remove("is-hidden")}function $(){document.querySelector(".end-message").classList.add("is-hidden")}const O=document.querySelector(".search-form"),x=document.querySelector(".load-more");let i=1,d="",c=0;P();O.addEventListener("submit",B);x.addEventListener("click",A);async function B(e){e.preventDefault();const s=e.target.elements.searchQuery.value.trim();if(!s){a.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}d=s,i=1,L(),$(),y();try{const r=await u(d,i);if(c=r.totalHits,R(),!r.hits.length){a.error({title:"Error",message:"No images found. Please try another query!",position:"topRight"});return}m(r.hits),h(),H(r.hits.length)&&p(),a.success({title:"Success",message:`Found ${c} images`,position:"topRight"})}catch(r){b(r)}finally{g()}}async function A(){i++,y(),L();try{const e=await u(d,i);m(e.hits),h(),_(),I()?M():p()}catch(e){b(e)}finally{g()}}function H(e){return e>=15&&i*15<c}function I(){return i*15>=c}function _(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function b(e){console.error("Error:",e),a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}
//# sourceMappingURL=index.js.map
